// Built-in material properties database

window.materialDB = {
  PLA: {
    name: 'PLA',
    fullName: 'Polylactic Acid',
    nozzleMin: 190, nozzleMax: 220,
    bedMin: 50, bedMax: 65,
    difficulty: 'Easy',
    strength: 'Moderate',
    flexibility: 'Low',
    uvResistance: 'Poor',
    heatResistance: 'Low (~55°C)',
    foodSafe: 'Conditionally (check manufacturer)',
    moistureSensitive: 'Low',
    needsEnclosure: false,
    bedAdhesion: 'Excellent on PEI, glass, BuildTak',
    dryingTemp: 50, dryingTime_hr: 4,
    notes: 'Best all-around starter material. Biodegradable. Brittle under stress.',
    printerSupport: ['bambu_a1', 'kobra_s1']
  },
  'PLA+': {
    name: 'PLA+',
    fullName: 'Enhanced PLA',
    nozzleMin: 200, nozzleMax: 230,
    bedMin: 55, bedMax: 65,
    difficulty: 'Easy',
    strength: 'Moderate-High',
    flexibility: 'Low-Moderate',
    uvResistance: 'Poor',
    heatResistance: 'Low (~60°C)',
    foodSafe: 'No',
    moistureSensitive: 'Low',
    needsEnclosure: false,
    bedAdhesion: 'Excellent',
    dryingTemp: 50, dryingTime_hr: 4,
    notes: 'Tougher than standard PLA with slightly better layer adhesion.',
    printerSupport: ['bambu_a1', 'kobra_s1']
  },
  PETG: {
    name: 'PETG',
    fullName: 'Polyethylene Terephthalate Glycol',
    nozzleMin: 220, nozzleMax: 250,
    bedMin: 70, bedMax: 85,
    difficulty: 'Moderate',
    strength: 'High',
    flexibility: 'Moderate',
    uvResistance: 'Good',
    heatResistance: 'Moderate (~75°C)',
    foodSafe: 'Yes (check manufacturer)',
    moistureSensitive: 'Moderate',
    needsEnclosure: false,
    bedAdhesion: 'Good — can stick too well to bare PEI, use glue stick as release agent',
    dryingTemp: 65, dryingTime_hr: 6,
    notes: 'Great balance of strength and ease. Watch for stringing.',
    printerSupport: ['bambu_a1', 'kobra_s1']
  },
  TPU: {
    name: 'TPU',
    fullName: 'Thermoplastic Polyurethane',
    nozzleMin: 210, nozzleMax: 240,
    bedMin: 40, bedMax: 60,
    difficulty: 'Moderate-Hard',
    strength: 'High (impact)',
    flexibility: 'Very High',
    uvResistance: 'Good',
    heatResistance: 'Moderate (~80°C)',
    foodSafe: 'No',
    moistureSensitive: 'High',
    needsEnclosure: false,
    bedAdhesion: 'Good',
    dryingTemp: 50, dryingTime_hr: 8,
    notes: 'Flexible/rubbery material. Print slow (20-40mm/s). Disable retraction or keep minimal.',
    printerSupport: ['bambu_a1', 'kobra_s1']
  },
  ABS: {
    name: 'ABS',
    fullName: 'Acrylonitrile Butadiene Styrene',
    nozzleMin: 230, nozzleMax: 260,
    bedMin: 90, bedMax: 110,
    difficulty: 'Hard',
    strength: 'High',
    flexibility: 'Moderate',
    uvResistance: 'Poor',
    heatResistance: 'High (~100°C)',
    foodSafe: 'No',
    moistureSensitive: 'Low',
    needsEnclosure: true,
    bedAdhesion: 'Moderate — warps without enclosure. Use ABS slurry or glue stick.',
    dryingTemp: 60, dryingTime_hr: 4,
    notes: 'Strong and heat-resistant but warps easily. Needs enclosure and good ventilation (fumes).',
    printerSupport: ['kobra_s1']
  },
  ASA: {
    name: 'ASA',
    fullName: 'Acrylonitrile Styrene Acrylate',
    nozzleMin: 235, nozzleMax: 260,
    bedMin: 90, bedMax: 110,
    difficulty: 'Hard',
    strength: 'High',
    flexibility: 'Moderate',
    uvResistance: 'Excellent',
    heatResistance: 'High (~100°C)',
    foodSafe: 'No',
    moistureSensitive: 'Low',
    needsEnclosure: true,
    bedAdhesion: 'Moderate — similar to ABS, use enclosure',
    dryingTemp: 60, dryingTime_hr: 4,
    notes: 'UV-resistant version of ABS. Best for outdoor parts. Needs enclosure.',
    printerSupport: ['kobra_s1']
  },
  Nylon: {
    name: 'Nylon',
    fullName: 'Polyamide (PA)',
    nozzleMin: 240, nozzleMax: 270,
    bedMin: 70, bedMax: 90,
    difficulty: 'Hard',
    strength: 'Very High',
    flexibility: 'High',
    uvResistance: 'Moderate',
    heatResistance: 'High (~110°C)',
    foodSafe: 'Conditionally',
    moistureSensitive: 'Very High',
    needsEnclosure: true,
    bedAdhesion: 'Poor — use PVA glue or garolite bed surface',
    dryingTemp: 70, dryingTime_hr: 12,
    notes: 'Extremely strong and flexible. Must be dried before printing. Absorbs moisture quickly.',
    printerSupport: []
  },
  PVA: {
    name: 'PVA',
    fullName: 'Polyvinyl Alcohol',
    nozzleMin: 190, nozzleMax: 220,
    bedMin: 45, bedMax: 60,
    difficulty: 'Moderate',
    strength: 'Low',
    flexibility: 'Low',
    uvResistance: 'N/A',
    heatResistance: 'Low',
    foodSafe: 'No',
    moistureSensitive: 'Extremely High',
    needsEnclosure: false,
    bedAdhesion: 'Good',
    dryingTemp: 45, dryingTime_hr: 10,
    notes: 'Water-soluble support material. Use with PLA for complex supports. Must keep dry.',
    printerSupport: ['bambu_a1']
  },
  HIPS: {
    name: 'HIPS',
    fullName: 'High Impact Polystyrene',
    nozzleMin: 220, nozzleMax: 250,
    bedMin: 90, bedMax: 110,
    difficulty: 'Moderate',
    strength: 'Moderate',
    flexibility: 'Low',
    uvResistance: 'Poor',
    heatResistance: 'Moderate (~80°C)',
    foodSafe: 'No',
    moistureSensitive: 'Low',
    needsEnclosure: true,
    bedAdhesion: 'Moderate',
    dryingTemp: 60, dryingTime_hr: 4,
    notes: 'Dissolves in limonene. Used as support for ABS prints.',
    printerSupport: []
  },
  PC: {
    name: 'PC',
    fullName: 'Polycarbonate',
    nozzleMin: 260, nozzleMax: 300,
    bedMin: 100, bedMax: 120,
    difficulty: 'Expert',
    strength: 'Very High',
    flexibility: 'Moderate',
    uvResistance: 'Good',
    heatResistance: 'Very High (~130°C)',
    foodSafe: 'Conditionally',
    moistureSensitive: 'High',
    needsEnclosure: true,
    bedAdhesion: 'Poor — needs high bed temp and adhesive',
    dryingTemp: 80, dryingTime_hr: 8,
    notes: 'Extremely strong and heat-resistant. Requires all-metal hotend and enclosure.',
    printerSupport: []
  }
};
